name: CI

on:
  pull_request:
    branches:
      - master
      - development

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          yarn install

      - name: Run lint and type checks in parallel
        run: |
          yarn lint &
          yarn type-check &
          wait
